# Generated by Django 3.1.5 on 2021-01-16 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('clnumber', models.AutoField(primary_key=True, serialize=False)),
                ('clname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('conumber', models.AutoField(primary_key=True, serialize=False)),
                ('coname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.clazz')),
                ('cour', models.ManyToManyField(to='Register.Course')),
            ],
        ),
    ]
